var aminoacidos =[
        {"codon":"GCU",
        "AA":"Ala",
        "nombre":"Alanina"},
        {"codon":"GCC",
        "AA":"Ala",
        "nombre":"Alanina"},
        {"codon":"GCA",
        "AA":"Ala",
        "nombre":"Alanina"},
        {"codon":"GCG",
        "AA":"Ala",
        "nombre":"Alanina"},

        {"codon":"CGU",
        "AA":"Arg",
        "nombre":"Arginina"},
        {"codon":"CGC",
        "AA":"Arg",
        "nombre":"Arginina"},
        {"codon":"CGA",
        "AA":"Arg",
        "nombre":"Arginina"},
        {"codon":"CGG",
        "AA":"Arg",
        "nombre":"Arginina"},
        {"codon":"AGA",
        "AA":"Arg",
        "nombre":"Arginina"},
        {"codon":"AGG",
        "AA":"Arg",
        "nombre":"Arginina"},

        {"codon":"AAU",
        "AA":"Asn",
        "nombre":"Aspargina"},
        {"codon":"AAC",
        "AA":"Asn",
        "nombre":"Aspargina"},

        {"codon":"GAU",
        "AA":"Asp",
        "nombre":"Ácido Aspártico"},
        {"codon":"GAC",
        "AA":"Asp",
        "nombre":"Ácido Aspártico"},

      
        {"codon":"UGU",
        "AA":"Cys",
        "nombre":"Cisteína"},
        {"codon":"UGC",
        "AA":"Cys",
        "nombre":"Cisteína"},

        {"codon":"CAA",
        "AA":"Gln",
        "nombre":"Glutamina"},
        {"codon":"CAG",
        "AA":"Gln",
        "nombre":"Glutamina"},
        
        {"codon":"GAA",
        "AA":"Glu",
        "nombre":"Ácido Glutamínico"},
        {"codon":"GAG",
        "AA":"Glu",
        "nombre":"Ácido Glutamínico"},

        {"codon":"GGU",
        "AA":"Gly",
        "nombre":"Glicina"},
        {"codon":"GGC",
        "AA":"Gly",
        "nombre":"Glicina"},
        {"codon":"GGA",
        "AA":"Gly",
        "nombre":"Glicina"},
        {"codon":"GGG",
        "AA":"Gly",
        "nombre":"Glicina"},

        {"codon":"CAU",
        "AA":"His",
        "nombre":"Histidina"},
        {"codon":"CAC",
        "AA":"His",
        "nombre":"Histidina"},

        {"codon":"AUU",
        "AA":"Ile",
        "nombre":"Isoleucina"},
        {"codon":"AUC",
        "AA":"Ile",
        "nombre":"Isoleucina"},
        {"codon":"AUA",
        "AA":"Ile",
        "nombre":"Isoleucina"},

        {"codon":"UUA",
        "AA":"Leu",
        "nombre":"Leucina"},
        {"codon":"UUG",
        "AA":"Leu",
        "nombre":"Leucina"},
        {"codon":"CUU",
        "AA":"Leu",
        "nombre":"Leucina"},
        {"codon":"CUC",
        "AA":"Leu",
        "nombre":"Leucina"},
        {"codon":"CUA",
        "AA":"Leu",
        "nombre":"Leucina"},
        {"codon":"CUG",
        "AA":"Leu",
        "nombre":"Leucina"},

        {"codon":"AAA",
        "AA":"Lys",
        "nombre":"Lisina"},
        {"codon":"AAG",
        "AA":"Lys",
        "nombre":"Lisina"},

        {"codon":"AUG",
        "AA":"Met",
        "nombre":"Metionina"},

        {"codon":"UUU",
        "AA":"Phe",
        "nombre":"Fenialanina"},
        {"codon":"UUC",
        "AA":"Phe",
        "nombre":"Fenialanina"},

        {"codon":"CCU",
        "AA":"Pro",
        "nombre":"Prolina"},
        {"codon":"CCC",
        "AA":"Pro",
        "nombre":"Prolina"},
        {"codon":"CCA",
        "AA":"Pro",
        "nombre":"Prolina"},
        {"codon":"CCG",
        "AA":"Pro",
        "nombre":"Prolina"},

        {"codon":"UCU",
        "AA":"Ser",
        "nombre":"Serina"},
        {"codon":"UCC",
        "AA":"Ser",
        "nombre":"Serina"},
        {"codon":"UCA",
        "AA":"Ser",
        "nombre":"Serina"},
        {"codon":"UCG",
        "AA":"Ser",
        "nombre":"Serina"},
        {"codon":"AGU",
        "AA":"Ser",
        "nombre":"Serina"},
        {"codon":"AGC",
        "AA":"Ser",
        "nombre":"Serina"},

        {"codon":"ACU",
        "AA":"Thr",
        "nombre":"Treonina"},
        {"codon":"ACC",
        "AA":"Thr",
        "nombre":"Treonina"},
        {"codon":"ACA",
        "AA":"Thr",
        "nombre":"Treonina"},
        {"codon":"ACG",
        "AA":"Thr",
        "nombre":"Treonina"},

        {"codon":"UGG",
        "AA":"Trp",
        "nombre":"Triptofano"},

        {"codon":"UAU",
        "AA":"Tyr",
        "nombre":"Tirosina"},
        {"codon":"UAC",
        "AA":"Tyr",
        "nombre":"Tirosina"},

        {"codon":"GUU",
        "AA":"Val",
        "nombre":"Valina"},
        {"codon":"GUC",
        "AA":"Val",
        "nombre":"Valina"},
        {"codon":"GUA",
        "AA":"Val",
        "nombre":"Valina"},
        {"codon":"GUG",
        "AA":"Val",
        "nombre":"Valina"},

        {"codon":"UAG",
        "AA":"STOP",
        "nombre":"STOP"},
        {"codon":"UGA",
        "AA":"STOP",
        "nombre":"STOP"},
        {"codon":"UAA",
        "AA":"STOP",
        "nombre":"STOP"},

        {"codon":"AUG",
        "AA":"START",
        "nombre":"START"},
]
